### ISSUE TITLE
PROBLEM USING IN BLENDER 4.0

### ISSUE THREAD

**Issue by SakuraEntropia** [EmuMan/npr-face-shader#3]
Python: Traceback (most recent call last):
  File "C:\Users\David\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\npr-face-shader-main\npr_face_shader\interface.py", line 86, in execute
    nodes.create_material(
  File "C:\Users\David\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\npr-face-shader-main\npr_face_shader\nodes.py", line 97, in create_material
    new_material.node_tree.links.new(image_normal_node.outputs[0], node_group.inputs[3])
IndexError: bpy_prop_collection[index]: index 3 out of range, size 0

**Comment by EmuMan** [comment]
Sorry for the late response. It looks like node group interactions using BPY might be different in 4.0? I'll take a look and fix this within the next day.
